# Generated by Django 5.2.7 on 2025-10-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_roleupgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], default='consumer', max_length=20),
        ),
    ]
