# Generated by Django 5.2.7 on 2025-10-18 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleupgraderequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Role Upgrade Request', 'verbose_name_plural': 'Role Upgrade Requests'},
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
